#include "shopData.h"

std::unordered_map<WorldEnums , AllShopProperties> allShopItems = {
    {
        WorldEnums::CenterWorld,
        {
            {
                "shop1",
                {
                    {
                        "meat",
                        "resources/image/UI/shop/meat_icon.png",
                        20,
                        10
                    },
                    {
                        "meat2",
                        "resources/image/UI/shop/meat_icon.png",
                        20,
                        10
                    },
                    {
                        "meat3",
                        "resources/image/UI/shop/meat_icon.png",
                        20,
                        10
                    },
                    {
                        "meat4",
                        "resources/image/UI/shop/meat_icon.png",
                        50,
                        10
                    },
                    {
                        "meat5",
                        "resources/image/UI/shop/meat_icon.png",
                        20,
                        10
                    },
                }
            },
        }
    }
};